SELECT
    ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (
    SELECT DISTINCT(ID)
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (
        SELECT DISTINCT(ID)
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL)
)
ORDER BY ID ASC;