SELECT *
FROM (
SELECT
    A.CAR_ID,
    A.CAR_TYPE,
    ROUND((A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
LEFT JOIN (
    SELECT 
        CONCAT(CAR_ID) AS CAR_ID,
        1 AS RENT_STAT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= "2022-11-30"
        AND END_DATE >= "2022-11-01"
) AS B
    ON A.CAR_ID = B.CAR_ID
JOIN (
    SELECT 
        CAR_TYPE,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ("세단", "SUV")
        AND DURATION_TYPE = "30일 이상"
) AS C
    ON A.CAR_TYPE = C.CAR_TYPE
WHERE RENT_STAT IS NULL
) AS RE
WHERE FEE >= 500000
    AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;