SELECT
    YEAR(A.SALES_DATE) AS YEAR,
    MONTH(A.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(A.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(A.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS A
JOIN (
    SELECT
        USER_ID,
        JOINED
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS B
    ON A.USER_ID = B.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;