WITH RECURSIVE ECOLI_GENERATION AS (
    -- 1세대 (ROOT)
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 자식 세대
    SELECT
        E.ID,
        E.PARENT_ID,
        G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_GENERATION G
      ON E.PARENT_ID = G.ID
)

SELECT 
    COUNT(*) AS COUNT,
    GENERATION
FROM ECOLI_GENERATION
WHERE ID NOT IN (
    SELECT DISTINCT(PARENT_ID)
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;