SELECT
    A.CAR_ID,
    COALESCE(B.AVAILABILITY, "대여 가능")
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
LEFT OUTER JOIN (SELECT 
    CAR_ID,
    (CASE
        WHEN START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16" THEN "대여중"
        ELSE "대여 가능"
    END) AS "AVAILABILITY"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
HAVING AVAILABILITY = "대여중") AS B
    ON A.CAR_ID = B.CAR_ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC;
