WITH RECURSIVE CC AS (
    SELECT 0 AS RNUM
    UNION ALL
    SELECT RNUM + 1 FROM CC
    WHERE RNUM < 23
)

SELECT
    RNUM AS HOUR,
    COALESCE(COUNTS, 0) AS COUNT
FROM CC
LEFT OUTER JOIN (
SELECT
    HOUR,
    COUNT(*) AS COUNTS
FROM (SELECT
    HOUR(DATETIME) AS HOUR
FROM ANIMAL_OUTS) AS A
GROUP BY HOUR
ORDER BY HOUR ASC
) AS A
    ON CC.RNUM = A.HOUR