-- 코드를 입력하세요
SELECT 
    data.FLAVOR
FROM FIRST_HALF AS data INNER JOIN ICECREAM_INFO AS info
ON data.FLAVOR = info.FLAVOR
WHERE TOTAL_ORDER > 3000
    AND INGREDIENT_TYPE = "fruit_based"
ORDER BY TOTAL_ORDER DESC;