SELECT 
    A.ID AS ID,
    B.FISH_NAME,
    A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
    ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS C
    ON A.FISH_TYPE = C.FISH_TYPE
        AND A.LENGTH = C.LENGTH
ORDER BY ID ASC;