SELECT
    CONCAT("/home/grep/src/", G.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT)
FROM USED_GOODS_BOARD AS G
JOIN USED_GOODS_FILE AS F
ON G.BOARD_ID = F.BOARD_ID
WHERE G.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;