SELECT
    F.CATEGORY,
    F.PRICE AS MAX_PRICE,
    F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F
JOIN (
    SELECT
        CATEGORY,
        MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
    GROUP BY CATEGORY
) AS B
ON F.CATEGORY = B.CATEGORY
    AND F.PRICE = B.PRICE
ORDER BY MAX_PRICE DESC;